// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Pancake

#ifndef _PANCAKE_UI_H
#define _PANCAKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_OverviewScreen
void ui_OverviewScreen_screen_init(void);
extern lv_obj_t *ui_OverviewScreen;
extern lv_obj_t *ui_LMotor;
extern lv_obj_t *ui_RMotor;
extern lv_obj_t *ui_MotorEnable;
extern lv_obj_t *ui_Direction;
extern lv_obj_t *ui_DirectionLabel;
extern lv_obj_t *ui_MainLabel1;
extern lv_obj_t *ui_MainLabel2;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
